GET http://localhost:5000/api/rooms

###
GET http://localhost:5000/api/rooms/1

###
GET http://localhost:5000/api/services

###
GET http://localhost:5000/api/activities

###
GET http://localhost:5000/api/reviews

###
POST http://localhost:5000/api/reviews
Content-Type: application/json
Authorization: BEARER {{authToken}}

{
  "message": "Test Review Message"
}

###
POST http://localhost:5000/api/forum/1
Content-Type: application/json
Authorization: BEARER {{authToken}}

{
  "message": "Test Message Inside A Thread"
}

###
POST http://localhost:5000/api/users/signup
Content-Type: application/json

{
  "name": "John Wayne",
  "email": "john@wayne.com",
  "password": "john@wayne"
}

###
# @name login
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "john@wayne.com",
  "password": "john@wayne"
}

###
GET http://localhost:5000/api/users
Authorization: BEARER {{authToken}}

###
PUT http://localhost:5000/api/users/edit-image
Content-Type: application/json
Authorization: BEARER {{authToken}}

{
  "image": "Test Image URL"
}

###
@authToken = {{login.response.body.token}}